
development:
  adapter: postgresql
  encoding: unicode
  database: design_melodrama_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: design_melodrama_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: design_melodrama_production
  pool: 5

